export default [
    {
        "id": "lksdfjhfljqkhr98124ywejknfjkd",
        "img": "https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_UY209_CR0,0,140,209_AL_.jpg",
        "title": "Aquaman",
        "date": "2018",
        "certificate": "PG-13",
        "duration": "143",
        "genres": ["Action ", "Adventure ", "Fantasy ", "Sci-Fi "],
        "metascore": "53",
        "text": "Arthur Curry learns that he is the heir to the underwater kingdom of Atlantis, and must step forward to lead his people and be a hero to the world.",
        "director": "James Wan",
        "stars": ["Jason Momoa", "Amber Heard", "Willem Dafoe", "Patrick Wilson"],
        "trailer": "https://www.youtube.com/embed/WDkg3h8PCVU",
        "uniqueTitle": "WDkg3h8PCVU"
    },
    {
        "id": "lkssdfeefdsfsddskhr98124ywejknfjkd",
        "img":"https://m.media-amazon.com/images/M/MV5BOTM3NzE5OTE1Nl5BMl5BanBnXkFtZTgwNzQwNjM3NjM@._V1_UY209_CR0,0,140,209_AL_.jpg",
        "title": "Bumblebee",
        "date": "2018",
        "certificate": "PG-13",
        "duration": "113",
        "genres": ["Action ", "Adventure ", "Sci-Fi "],
        "metascore": "70",
        "text": "On the run in the year of 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken.",
        "director": "Travis Knight",
        "stars": ["Hailee Steinfeld", "Dylan O'Brien", "Megyn Price", "John Cena"],
        "trailer": "https://www.youtube.com/embed/lcwmDAYt22k",
        "uniqueTitle": "lcwmDAYt22k"
    },
    {
        "id": "MV5BMjM0MjEzOTQ1NF5BMl5BanBnXkFtZTgwODg4ODc5NjM",
        "img": "https://m.media-amazon.com/images/M/MV5BMjM0MjEzOTQ1NF5BMl5BanBnXkFtZTgwODg4ODc5NjM@._V1_UY209_CR0,0,140,209_AL_.jpg",
        "title": "Mary Poppins Returns",
        "date": "2018",
        "certificate": "PG",
        "duration": "130",
        "genres": ["Comedy ", "Family ", "Fantasy ", "Musical"],
        "metascore": "65",
        "text": "Decades after her original visit, the magical nanny returns to help the Banks siblings and Michael's children through a difficult time in their lives.",
        "director": "Rob Marshall",
        "stars": [" Emily Blunt", " Lin-Manuel Miranda", " Ben Whishaw", " Emily Mortimer"],
        "trailer": "https://www.youtube.com/embed/-3jsfXDZLIY",
        "uniqueTitle": "-3jsfXDZLIY"
    },
    {
        "id": "MV5BMjQ2MjI5Njk0MF5BMl5BanBnXkFtZTgwNDQ2NzczNTM",
        "img":"https://m.media-amazon.com/images/M/MV5BMjQ2MjI5Njk0MF5BMl5BanBnXkFtZTgwNDQ2NzczNTM@._V1_UY209_CR0,0,140,209_AL_.jpg",
        "title": "Second Act",
        "date": "2018",
        "certificate": "PG-13",
        "duration": "103",
        "genres": ["Comedy ", "Romance"],
        "metascore": "49",
        "text": "A big box store worker reinvents her life and her life-story and shows Madison Avenue what street smarts can do.",
        "director": "Peter Segal",
        "stars": ["Jennifer Lopez ", "Vanessa Hudgens ", "Leah Remini ", "Treat Williams"],
        "trailer": "https://www.youtube.com/embed/YsVo5necW6Q",
        "uniqueTitle": "YsVo5necW6Q"
    }
]